<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_node_insert().
 */
function ad_general_node_insert(NodeInterface $node) {
  if ($node->getType() == 'company') {
    if (!$node->get('field_company_website')->getString()) {
      $messenger = \Drupal::messenger();
      $messenger->addMessage('Please consider adding a website for your company. It’s not mandatory, but it’s a good way of showing people what you do.');
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ad_general_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'node_company_form') {
    $form['#validate'][] = 'ad_general_node_form_validate';
  }
  elseif ($form_id == 'send_email_form') {
    $form['#validate'][] = 'ad_general_node_form_validate';
  }
}

/**
 * Implements hook_form_validate().
 */
function ad_general_node_form_validate(&$form, FormStateInterface &$form_state) {
  if (strpos($form_state->getValue('field_company_website')[0]['value'], 'no-replay') !== FALSE && $form['#attributes']['class'][0] == 'node-company-form') {
    $form_state->setErrorByName('field_company_website', t('Please enter a valid response email!'));
  }
  if (!\Drupal::service('email.validator')->isValid($form_state->getValue('email')) && $form['#attributes']['class'][0] == 'send-email-form') {
    $form_state->setErrorByName('email', t('Enter a valid email address'));
  }
}

/**
 * Callback for form_send_mail submit.
 *
 * @param array $form
 *   The form.
 * @param FormStateInterface $form_state
 *   The FormStateInterface.
 */
function ad_general_send_mail(&$form, FormStateInterface &$form_state) {

}

/**
 * Implements hook_mail().
 */
function ad_general_mail($key, &$message, $params) {
  switch ($key) {
    case 'ad_general_email':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['name'] . ' ' . 'invited you to' . ' ' . $params['event_title'];
      $message['body'][] = 'Check out this event by ' . $params['company_name'] . '!';
      $message['body'][] = $params['event_url'];
      break;
  }
}
